import type { Metadata } from 'next';
import './globals.css';
import { Comfortaa } from 'next/font/google';
import Head from 'next/head';

const comfortaa = Comfortaa({
  variable: '--comfortaa',
  subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Ранкова</title>
      </Head>
      <body className={`${comfortaa.className}`}>{children}</body>
    </html>
  );
}
